name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: ğŸ”„ Repo klonlash
        uses: actions/checkout@v3

      - name: ğŸ“¦ Dependencies oâ€˜rnatish
        run: npm install

      - name: ğŸ›  Build qilish
        run: npm run build

      - name: ğŸ“ Fayllarni kerakli joyga koâ€˜chirish
        run: |
          rm -rf /home/ubuntu/app-backend
          mkdir -p /home/ubuntu/app-backend
          cp -r . /home/ubuntu/app-backend

      - name: ğŸ” Servisni qayta ishga tushirish
        run: |
          sudo systemctl restart backend.service
